# Generated by Django 4.2.10 on 2024-08-19 16:10

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_price'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='course',
            managers=[
                ('available', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
